export default {
    background: '#ffffff',
    backgroundComplementary: '#313131',
    text: '#313131',
    textComplementary: '#ffffff',
    selectionBackground: '#3131311a',
    paperBackground: '#fdfdfd',
    border: '#ededed',
    active: '#ffa500',
    activeLight: '#ffd700',
    activeDark: '#ff8c00',
    activeText: '#ffffff',
    brand: '#00adff',
    brandLight: '#58c4f7',
    brandDark: '#028dcf',
    grayText: 'gray',
    formBorder: 'lightgray',
    formBorderActive: 'gray',
};